server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nsh_guild_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: YOUR_PROD_SECRET_KEY
  expiration: 86400000 # 24小时

springdoc:
  swagger-ui:
    url: "/v3/api-docs"
    path: "/swagger-ui.html"
    display-url: true
    enable: true
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
    use-root-path: true
    input-header-tokens:
      Authorization: Bearer <token>

logging:
  level:
    xyz.bfdwdd.nshguildmanageb: DEBUG