server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: dev-secret-key
  expiration: 3600000 # 1??

springdoc:
  swagger-ui:
    url: "/v3/api-docs"
    path: "/swagger-ui.html"
    display-url: true
    enable: true
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
    use-root-path: true
    input-header-tokens:
      Authorization: Bearer <token>

logging:
  level:
    xyz.bfdwdd.nshguildmanageb: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console